// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Applications -->Single Application.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const example = prowlarr.Application.getApplication({
 *     name: "Example",
 * });
 * ```
 */
export function getApplication(args: GetApplicationArgs, opts?: pulumi.InvokeOptions): Promise<GetApplicationResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Application/getApplication:getApplication", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getApplication.
 */
export interface GetApplicationArgs {
    /**
     * Application name.
     */
    name: string;
}

/**
 * A collection of values returned by getApplication.
 */
export interface GetApplicationResult {
    /**
     * Anime sync categories.
     */
    readonly animeSyncCategories: number[];
    /**
     * API key.
     */
    readonly apiKey: string;
    /**
     * Base URL.
     */
    readonly baseUrl: string;
    /**
     * Application configuration template.
     */
    readonly configContract: string;
    /**
     * Application ID.
     */
    readonly id: number;
    /**
     * Application implementation name.
     */
    readonly implementation: string;
    /**
     * Application name.
     */
    readonly name: string;
    /**
     * Prowlarr URL.
     */
    readonly prowlarrUrl: string;
    /**
     * Sync categories.
     */
    readonly syncCategories: number[];
    /**
     * Sync level.
     */
    readonly syncLevel: string;
    /**
     * List of associated tags.
     */
    readonly tags: number[];
}
/**
 * <!-- subcategory:Applications -->Single Application.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const example = prowlarr.Application.getApplication({
 *     name: "Example",
 * });
 * ```
 */
export function getApplicationOutput(args: GetApplicationOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetApplicationResult> {
    return pulumi.output(args).apply((a: any) => getApplication(a, opts))
}

/**
 * A collection of arguments for invoking getApplication.
 */
export interface GetApplicationOutputArgs {
    /**
     * Application name.
     */
    name: pulumi.Input<string>;
}
