// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Applications -->List all available Sync Profiles.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const example = prowlarr.Application.getSyncProfiles({});
 * ```
 */
export function getSyncProfiles(opts?: pulumi.InvokeOptions): Promise<GetSyncProfilesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Application/getSyncProfiles:getSyncProfiles", {
    }, opts);
}

/**
 * A collection of values returned by getSyncProfiles.
 */
export interface GetSyncProfilesResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * Sync Profile list.
     */
    readonly syncProfiles: outputs.Application.GetSyncProfilesSyncProfile[];
}
