// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Indexer Proxies -->List all available Indexer Proxies.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const example = prowlarr.IndexerProxy.getIndexerProxies({});
 * ```
 */
export function getIndexerProxies(opts?: pulumi.InvokeOptions): Promise<GetIndexerProxiesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:IndexerProxy/getIndexerProxies:getIndexerProxies", {
    }, opts);
}

/**
 * A collection of values returned by getIndexerProxies.
 */
export interface GetIndexerProxiesResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * Indexer Client list.
     */
    readonly indexerProxies: outputs.IndexerProxy.GetIndexerProxiesIndexerProxy[];
}
