// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Indexers -->Indexer schema definition.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const test = prowlarr.Indexer.getIndexerSchema({
 *     name: "AlphaRatio",
 * });
 * ```
 */
export function getIndexerSchema(args: GetIndexerSchemaArgs, opts?: pulumi.InvokeOptions): Promise<GetIndexerSchemaResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Indexer/getIndexerSchema:getIndexerSchema", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getIndexerSchema.
 */
export interface GetIndexerSchemaArgs {
    /**
     * Indexer name.
     */
    name: string;
}

/**
 * A collection of values returned by getIndexerSchema.
 */
export interface GetIndexerSchemaResult {
    /**
     * Indexer configuration template.
     */
    readonly configContract: string;
    /**
     * Indexer description.
     */
    readonly description: string;
    /**
     * Indexer encoding.
     */
    readonly encoding: string;
    /**
     * Set of configuration fields.
     */
    readonly fields: outputs.Indexer.GetIndexerSchemaField[];
    /**
     * Schema ID.
     */
    readonly id: number;
    /**
     * Indexer implementation name.
     */
    readonly implementation: string;
    /**
     * List of available URLs.
     */
    readonly indexerUrls: string[];
    /**
     * Language.
     */
    readonly language: string;
    /**
     * List of legacy URLs.
     */
    readonly legacyUrls: string[];
    /**
     * Indexer name.
     */
    readonly name: string;
    /**
     * Privacy.
     */
    readonly privacy: string;
    /**
     * Protocol. Valid values are 'usenet' and 'torrent'.
     */
    readonly protocol: string;
}
/**
 * <!-- subcategory:Indexers -->Indexer schema definition.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const test = prowlarr.Indexer.getIndexerSchema({
 *     name: "AlphaRatio",
 * });
 * ```
 */
export function getIndexerSchemaOutput(args: GetIndexerSchemaOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIndexerSchemaResult> {
    return pulumi.output(args).apply((a: any) => getIndexerSchema(a, opts))
}

/**
 * A collection of arguments for invoking getIndexerSchema.
 */
export interface GetIndexerSchemaOutputArgs {
    /**
     * Indexer name.
     */
    name: pulumi.Input<string>;
}
