// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Indexers -->Single Indexer.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const test = prowlarr.Indexer.getIndexer({
 *     name: "Example",
 * });
 * ```
 */
export function getIndexer(args: GetIndexerArgs, opts?: pulumi.InvokeOptions): Promise<GetIndexerResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Indexer/getIndexer:getIndexer", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getIndexer.
 */
export interface GetIndexerArgs {
    /**
     * Indexer name.
     */
    name: string;
}

/**
 * A collection of values returned by getIndexer.
 */
export interface GetIndexerResult {
    /**
     * Application profile ID.
     */
    readonly appProfileId: number;
    /**
     * Indexer configuration template.
     */
    readonly configContract: string;
    /**
     * Enable RSS flag.
     */
    readonly enable: boolean;
    /**
     * Set of configuration fields.
     */
    readonly fields: outputs.Indexer.GetIndexerField[];
    /**
     * Indexer ID.
     */
    readonly id: number;
    /**
     * Indexer implementation name.
     */
    readonly implementation: string;
    /**
     * Language.
     */
    readonly language: string;
    /**
     * Indexer name.
     */
    readonly name: string;
    /**
     * Priority.
     */
    readonly priority: number;
    /**
     * Privacy.
     */
    readonly privacy: string;
    /**
     * Protocol. Valid values are 'usenet' and 'torrent'.
     */
    readonly protocol: string;
    /**
     * List of associated tags.
     */
    readonly tags: number[];
}
/**
 * <!-- subcategory:Indexers -->Single Indexer.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const test = prowlarr.Indexer.getIndexer({
 *     name: "Example",
 * });
 * ```
 */
export function getIndexerOutput(args: GetIndexerOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIndexerResult> {
    return pulumi.output(args).apply((a: any) => getIndexer(a, opts))
}

/**
 * A collection of arguments for invoking getIndexer.
 */
export interface GetIndexerOutputArgs {
    /**
     * Indexer name.
     */
    name: pulumi.Input<string>;
}
