// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetIndexerArgs, GetIndexerResult, GetIndexerOutputArgs } from "./getIndexer";
export const getIndexer: typeof import("./getIndexer").getIndexer = null as any;
export const getIndexerOutput: typeof import("./getIndexer").getIndexerOutput = null as any;
utilities.lazyLoad(exports, ["getIndexer","getIndexerOutput"], () => require("./getIndexer"));

export { GetIndexerSchemaArgs, GetIndexerSchemaResult, GetIndexerSchemaOutputArgs } from "./getIndexerSchema";
export const getIndexerSchema: typeof import("./getIndexerSchema").getIndexerSchema = null as any;
export const getIndexerSchemaOutput: typeof import("./getIndexerSchema").getIndexerSchemaOutput = null as any;
utilities.lazyLoad(exports, ["getIndexerSchema","getIndexerSchemaOutput"], () => require("./getIndexerSchema"));

export { GetIndexerSchemasResult } from "./getIndexerSchemas";
export const getIndexerSchemas: typeof import("./getIndexerSchemas").getIndexerSchemas = null as any;
utilities.lazyLoad(exports, ["getIndexerSchemas"], () => require("./getIndexerSchemas"));

export { GetIndexersResult } from "./getIndexers";
export const getIndexers: typeof import("./getIndexers").getIndexers = null as any;
utilities.lazyLoad(exports, ["getIndexers"], () => require("./getIndexers"));

export { IndexerArgs, IndexerState } from "./indexer";
export type Indexer = import("./indexer").Indexer;
export const Indexer: typeof import("./indexer").Indexer = null as any;
utilities.lazyLoad(exports, ["Indexer"], () => require("./indexer"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "prowlarr:Indexer/indexer:Indexer":
                return new Indexer(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("prowlarr", "Indexer/indexer", _module)
