// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -->Tag list with their associated resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const example = prowlarr.Tag.getTagsDetails({});
 * ```
 */
export function getTagsDetails(opts?: pulumi.InvokeOptions): Promise<GetTagsDetailsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Tag/getTagsDetails:getTagsDetails", {
    }, opts);
}

/**
 * A collection of values returned by getTagsDetails.
 */
export interface GetTagsDetailsResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * Tag list.
     */
    readonly tags: outputs.Tag.GetTagsDetailsTag[];
}
