// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Indexer Proxies -->Generic Indexer Proxy resource. When possible use a specific resource instead.
 * For more information refer to [Indexer Proxy](https://wiki.servarr.com/prowlarr/settings#indexer-proxies).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@maienm/pulumi-prowlarr";
 *
 * const example = new prowlarr.indexerproxies.IndexerProxy("example", {
 *     configContract: "FlareSolverrSettings",
 *     host: "http://localhost:8191/",
 *     implementation: "FlareSolverr",
 *     name: "Example",
 *     requestTimeout: 60,
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import prowlarr:IndexerProxies/indexerProxy:IndexerProxy example 1
 * ```
 */
export class IndexerProxy extends pulumi.CustomResource {
    /**
     * Get an existing IndexerProxy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IndexerProxyState, opts?: pulumi.CustomResourceOptions): IndexerProxy {
        return new IndexerProxy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'prowlarr:IndexerProxies/indexerProxy:IndexerProxy';

    /**
     * Returns true if the given object is an instance of IndexerProxy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IndexerProxy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IndexerProxy.__pulumiType;
    }

    /**
     * IndexerProxy configuration template.
     */
    public readonly configContract!: pulumi.Output<string>;
    /**
     * host.
     */
    public readonly host!: pulumi.Output<string>;
    /**
     * IndexerProxy implementation name.
     */
    public readonly implementation!: pulumi.Output<string>;
    /**
     * Indexer Proxy name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Password.
     */
    public readonly password!: pulumi.Output<string>;
    /**
     * Port.
     */
    public readonly port!: pulumi.Output<number>;
    /**
     * Request timeout.
     */
    public readonly requestTimeout!: pulumi.Output<number>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;
    /**
     * Username.
     */
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a IndexerProxy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IndexerProxyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IndexerProxyArgs | IndexerProxyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IndexerProxyState | undefined;
            resourceInputs["configContract"] = state ? state.configContract : undefined;
            resourceInputs["host"] = state ? state.host : undefined;
            resourceInputs["implementation"] = state ? state.implementation : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["port"] = state ? state.port : undefined;
            resourceInputs["requestTimeout"] = state ? state.requestTimeout : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as IndexerProxyArgs | undefined;
            if ((!args || args.configContract === undefined) && !opts.urn) {
                throw new Error("Missing required property 'configContract'");
            }
            if ((!args || args.implementation === undefined) && !opts.urn) {
                throw new Error("Missing required property 'implementation'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["configContract"] = args ? args.configContract : undefined;
            resourceInputs["host"] = args ? args.host : undefined;
            resourceInputs["implementation"] = args ? args.implementation : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["port"] = args ? args.port : undefined;
            resourceInputs["requestTimeout"] = args ? args.requestTimeout : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["username"] = args ? args.username : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IndexerProxy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IndexerProxy resources.
 */
export interface IndexerProxyState {
    /**
     * IndexerProxy configuration template.
     */
    configContract?: pulumi.Input<string>;
    /**
     * host.
     */
    host?: pulumi.Input<string>;
    /**
     * IndexerProxy implementation name.
     */
    implementation?: pulumi.Input<string>;
    /**
     * Indexer Proxy name.
     */
    name?: pulumi.Input<string>;
    /**
     * Password.
     */
    password?: pulumi.Input<string>;
    /**
     * Port.
     */
    port?: pulumi.Input<number>;
    /**
     * Request timeout.
     */
    requestTimeout?: pulumi.Input<number>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Username.
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IndexerProxy resource.
 */
export interface IndexerProxyArgs {
    /**
     * IndexerProxy configuration template.
     */
    configContract: pulumi.Input<string>;
    /**
     * host.
     */
    host?: pulumi.Input<string>;
    /**
     * IndexerProxy implementation name.
     */
    implementation: pulumi.Input<string>;
    /**
     * Indexer Proxy name.
     */
    name: pulumi.Input<string>;
    /**
     * Password.
     */
    password?: pulumi.Input<string>;
    /**
     * Port.
     */
    port?: pulumi.Input<number>;
    /**
     * Request timeout.
     */
    requestTimeout?: pulumi.Input<number>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Username.
     */
    username?: pulumi.Input<string>;
}
