// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Applications -->Single Sync Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const test = prowlarr.Applications.getSyncProfile({
 *     name: "Example",
 * });
 * ```
 */
export function getSyncProfile(args: GetSyncProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetSyncProfileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Applications/getSyncProfile:getSyncProfile", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSyncProfile.
 */
export interface GetSyncProfileArgs {
    /**
     * Name.
     */
    name: string;
}

/**
 * A collection of values returned by getSyncProfile.
 */
export interface GetSyncProfileResult {
    /**
     * Enable automatic search flag.
     */
    readonly enableAutomaticSearch: boolean;
    /**
     * Enable interactive search flag.
     */
    readonly enableInteractiveSearch: boolean;
    /**
     * Enable RSS flag.
     */
    readonly enableRss: boolean;
    /**
     * Sync Profile ID.
     */
    readonly id: number;
    /**
     * Minimum seeders.
     */
    readonly minimumSeeders: number;
    /**
     * Name.
     */
    readonly name: string;
}
/**
 * <!-- subcategory:Applications -->Single Sync Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const test = prowlarr.Applications.getSyncProfile({
 *     name: "Example",
 * });
 * ```
 */
export function getSyncProfileOutput(args: GetSyncProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSyncProfileResult> {
    return pulumi.output(args).apply((a: any) => getSyncProfile(a, opts))
}

/**
 * A collection of arguments for invoking getSyncProfile.
 */
export interface GetSyncProfileOutputArgs {
    /**
     * Name.
     */
    name: pulumi.Input<string>;
}
