// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace Applications {
}

export namespace DownloadClients {
    export interface DownloadClientAria2Category {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientDelugeCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientFloodCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientFreeboxCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientHadoukenCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientNzbgetCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientNzbvortexCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientPneumaticCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientQbittorrentCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientRtorrentCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientSabnzbdCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientTorrentBlackholeCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientTorrentDownloadStationCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientTransmissionCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientUsenetBlackholeCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientUsenetDownloadStationCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientUtorrentCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

    export interface DownloadClientVuzeCategory {
        /**
         * List of categories.
         */
        categories?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Name of client category.
         */
        name?: pulumi.Input<string>;
    }

}

export namespace IndexerProxies {
}

export namespace Indexers {
    export interface IndexerField {
        /**
         * Bool value. Only one value must be filled out.
         */
        boolValue?: pulumi.Input<boolean>;
        /**
         * Field name.
         */
        name: pulumi.Input<string>;
        /**
         * Number value. Only one value must be filled out.
         */
        numberValue?: pulumi.Input<number>;
        /**
         * Sensitive string value. Only one value must be filled out.
         */
        sensitiveValue?: pulumi.Input<string>;
        /**
         * Set value. Only one value must be filled out.
         */
        setValues?: pulumi.Input<pulumi.Input<number>[]>;
        /**
         * Text value. Only one value must be filled out.
         */
        textValue?: pulumi.Input<string>;
    }
}

export namespace Notifications {
}

export namespace Tags {
}
