// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Indexers -->List all available Indexer Schemas.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prowlarr from "@pulumi/prowlarr";
 *
 * const example = prowlarr.Indexers.getIndexerSchemas({});
 * ```
 */
export function getIndexerSchemas(opts?: pulumi.InvokeOptions): Promise<GetIndexerSchemasResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prowlarr:Indexers/getIndexerSchemas:getIndexerSchemas", {
    }, opts);
}

/**
 * A collection of values returned by getIndexerSchemas.
 */
export interface GetIndexerSchemasResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * Indexer name list.
     */
    readonly indexerSchemas: string[];
}
